name: Deploy to Production on GKE cluster.
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/service:mkt-auth-service .

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/service:mkt-auth-service

      - name: pull difintion file
        run: curl -o auth-service.yml https://1fd8c0ce5eaea18fac2f3551890548070f061bf3@raw.githubusercontent.com/henryodinakamin/ConfigStore/master/k8s-market/deployments/auth-service.yml

      - name: Build number
        run: sed -ie "s/THIS_STRING_IS_REPLACED_DURING_BUILD/$(date)/g" auth-service.yml

      - name: kubectl - apply changes on deploymet on GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
          CLUSTER_NAME: min-portal-cluster
          ZONE_NAME: europe-west1-c
        with:
          args: apply -f auth-service.yml